### ISSUE TITLE
Error lunch

### ISSUE THREAD

**Issue by abariusav** [abariusav/doogee_mix_twrp#1]
```
**$ lunch omni_doogeemix-userdebug**
build/core/envsetup.mk:152: *** No config file found for TARGET_DEVICE doogeemix.  Stopping.
Your device can't be found in device sources..
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 353, in <module>
    fetch_device(device)
  File "build/tools/roomservice.py", line 321, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "build/tools/roomservice.py", line 81, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "build/tools/roomservice.py", line 58, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: doogeemix not found,exiting roomservice
build/core/envsetup.mk:152: *** No config file found for TARGET_DEVICE doogeemix.  Stopping.

** Don't have a product spec for: 'omni_doogeemix'
** Do you have the right repo manifest?

```

**Comment by abariusav** [comment]
Fixed. Thanks to the user "Tho" from the forum 4pda.ru
